### PR TITLE
Create release.yml

### PR DESCRIPTION
**Pull request by arjunraghurama**
Added a new workflow. Created release.yml to publish NuGet package upon code push to main branch.

### CODE REVIEW

**Review by Mirch — CHANGES_REQUESTED** [review]
The pipeline looks good so far, but it's missing the `create release` step mentioned in the issue. See more info here: https://github.com/actions/create-release

**Comment by arjunraghurama** [comment]
Updated the workflow with `create release` and `upload release asset`

**Review by Mirch — APPROVED** [review]

**Comment by Mirch** [comment]
Looks good! I'll merge it once we have a nuget account :)

**Comment by xmac11** [comment]
Welcome @arjunraghurama, I'd be better if you opened seperate PRs for different issues

**Pull request merged**
