### PR TITLE
Fixed failing build

### PR DESCRIPTION
**Pull request by xmac11**

### CODE REVIEW

**Comment by Mirch** [comment]
Damn, why did this not show up when I merged the other PR?

**Comment by xmac11** [comment]
I was wondering this too. My only guess would be that the check runs only when the PR is first opened, but in the meantime another merge might break it. Not familiar with this though, could be wrong.

**Comment by xmac11** [comment]
Account number:
8ff92d181cb09f18ef2a1b03badb5bf4a8962f7e5bb55641d0358d99bf7d5655

**Comment by itsnikhil** [comment]
Hi @xmac11 is this PR associated with any issue?

**Comment by xmac11** [comment]
@itsnikhil nope

**Comment by itsnikhil** [comment]
> @itsnikhil nope

Thanks, you will receive payment for this soon. But from next time please create an issue before submitting any PR as our payment system is designed in that way.

**Pull request merged**
