### PR TITLE
Hide internal API layers

### LINKED ISSUE #92: Hide the API layer
The developers using the SDK should only have access to the application layer (`Thenewboston.Nodes`), and not the lower level layers that are used to wrap the API and process the requests/responses. 

- the classes in these layers should be marked as `internal`;
- the namespaces should allow the test project to access the classes, so tests can still run normally.

### PR DESCRIPTION
**Pull request by arjunraghurama**
#92 

public -> internal

### CODE REVIEW

**Comment by Mirch** [comment]
I'll need some explanations here, as I don't want to make any mistake when merging it.

Does marking methods as internal in the test project make it so they can call the main project?
Also, what did you mark as internal in the main project?

**Comment by arjunraghurama** [comment]
Hey! I forgot to add the change details. I have made the API layer classes (Bank and Validator) as internal (from public) so that its accessible only in that assembly. In the main project Service layer classes are made internal.

**Comment by Mirch** [comment]
What about the tests? I see many changes there.

**Comment by arjunraghurama** [comment]
In Test projects, few helper methods were ```public static``` which were changed to `internal static`.

**Comment by Mirch** [comment]
Yup, I see that. But why?

**Comment by arjunraghurama** [comment]
For example in `AccountsServiceTests.cs ` we have a static method whose return type `AccountsService`  is less accessible than the method `BuildAccountsServiceMock` i.e. a `public` method is returning a `internal` class. To overcome this I have made those helper methods as internal. Also we can achieve the same by making the access specifiers for these helper methods as `private` (Have verified the same for AccountsServiceTests)

**Pull request merged**
